#!/bin/bash

# update apt then apt install
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt update
sudo apt upgrade
sudo apt install python2 python3 exa cmake neovim golang-go

# manual installs
if [[ $(command -v exa) ]]; then
	echo "exa already installed"
else
	cd /tmp
	wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/r/rust-exa/exa_0.9.0-4_amd64.deb
	sudo apt-get install ./exa_0.9.0-4_amd64.deb
fi

if [ -d '~/.nvm' ]; then
	echo "nvm already installed"
else
	cd /tmp
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
	nvm install 18
	nvm alias default 18
fi

if [[ $(command -v lazygit) ]]; then
	echo "lazygit already installed"
else
	cd /tmp
	cd lazygit
	git clone https://github.com/jesseduffield/lazygit.git
	go install
fi

# install tools from package registries
npm i -g yarn

