#!/usr/bin/env sh

LIMELIGHT=~/.config/limelight/limelight/bin/limelight

$LIMELIGHT -m config width            3
$LIMELIGHT -m config radius           10
$LIMELIGHT -m config placement        exterior
$LIMELIGHT -m config active_color     0xff30638e
$LIMELIGHT -m config normal_color     0x66003d5b

echo "limelight configuration loaded.."
